### ISSUE TITLE
Is it necessary for the changes of v0.3.0.1-2 on ATOMS?

### ISSUE THREAD

**Issue by Pingmin** [holgern/swt#1]
Do you forget or discard v0.3.0.1-2?
Please confirm this changes of "src/c/daubechies.c" in v0.3.0.1-2 on https://atoms.scilab.org/toolboxes/swt/ . It shows :

// Coefficent calcalated by Bob Strunz 2015
static const double db1[2]={     7.071067811865475244008443621048E-01,
...

Thanks!

**Comment by holgern** [comment]
Thank you, i fixed this.
